### ISSUE TITLE
Cannot clone this on Windows

### ISSUE THREAD

**Issue by LisaMc** [FredHutch/Oncoscape#6]
The file https://github.com/oncoscape/Oncoscape/blob/master/dataPackages/networks/DEMOdzMarkersAndTissues/prep/prep%3C4%3E contains the < and > characters which are not allowed for files on Windows. This makes it hard for users using Windows to contribute. Any chance that file could be renamed?

**Comment by LisaMc** [comment]
@robert-mcdermott is this fixed now?

**Comment by robert-mcdermott** [comment]
@LisaMc no the issue remains, I just received the following error trying to clone it to a Windows system:

```
error: Invalid path 'dataPackages/networks/DEMOdzMarkersAndTissues/prep/prep<4>
```

**Comment by robert-mcdermott** [comment]
@pshannon-bioc there is a file in the master branch with a filename that's invalid in Windows ('prep<4>') that's preventing the repo from being cloned on Windows systems. The full path to the problem file is below:

```
Oncoscape/dataPackages/networks/DEMOdzMarkersAndTissues/prep/prep<4>
```

The contents of the file appears to be a directory listing (ls -l) from your Mac.  Is it OK to just remove this file or does it serve a purpose?

**Comment by pshannon-bioc** [comment]
Please delete.  I don’t recognize this at all.   Will check in my version and clean up.

Thanks!

 - Paul
